### ISSUE TITLE
Loading animation doesn't work on Microsoft Edge

### ISSUE THREAD

**Issue by DropTable00** [Ali229/Postit#13]
![image](https://user-images.githubusercontent.com/42593012/46635249-b5d82200-cb21-11e8-9bb9-9915b369d20c.png)

When visiting any page on Microsoft Edge, the loading animation does not work. It sits still in the position shown in the picture above.

Only effects Microsoft Edge.

**Comment by DropTable00** [comment]
Updated issue: used to only be a problem for the users page, is now a problem on all pages.

**Comment by Ali229** [comment]
Microsoft Edge doesn't support .SVG animations.
