### ISSUE TITLE
Pages can be visited without logging in by entering the URL

### ISSUE THREAD

**Issue by DropTable00** [Ali229/Postit#15]
![image](https://user-images.githubusercontent.com/42593012/46635747-6d216880-cb23-11e8-8d9c-f8b8126a7211.png)
If the URL for a page is entered in the URL bar of a browser, the user will be taken to the page but with most elements not loaded. No data from the back end will load, they will only see a few front end things.

Effects all browsers.

Recreate: Enter "http://postit.markzeagler.com/users" in the URL bar of a web browser.

**Comment by EagleZR** [comment]
Fixed by reenabling AuthGuard
