### ISSUE TITLE
No error message for invalid input on password recovery

### ISSUE THREAD

**Issue by DropTable00** [Ali229/Postit#17]
![image](https://user-images.githubusercontent.com/42593012/46636168-0309c300-cb25-11e8-8f9b-687be5393fe8.png)
When attempting to recover a password, if an invalid username is entered, as shown above, the system does not display an error message. 

_EDIT:This also applies to entering a username that is not found in the database._

Effects all browsers.

Recreate: Use password recovery from the login page and enter an invalid value.

**Comment by EagleZR** [comment]
Fixed backend so error response is correctly thrown
