### ISSUE TITLE
Searching on event logs does not filter the event logs correctly

### ISSUE THREAD

**Issue by DropTable00** [Ali229/Postit#18]
![image](https://user-images.githubusercontent.com/42593012/46823880-60885480-cd5d-11e8-8543-073111093822.png)
![image](https://user-images.githubusercontent.com/42593012/46823916-79910580-cd5d-11e8-866c-1234ee5eaec8.png)
![image](https://user-images.githubusercontent.com/42593012/46824018-be1ca100-cd5d-11e8-89e8-95e0c3be42cb.png)

When searching on the event logs, some searches do not return the expected results. In the picture above you can see searching "admin" works correctly, filtering the event log by events with the word admin. However, searching for a specific user ID yields no change in the displayed data.

Affects all browsers.

Recreate: Enter a search term that will appear in a message in the event logs, then enter a number to search for a specific user ID. (NOTE: Searches are case sensitive. For example, if you search "logged" it will not work, you must search "Logged")

**Comment by EagleZR** [comment]
Filter working as expected for now. The 7 matches the timestamp text. Might later allow for table column to be specified in search. Closing for now
