### ISSUE TITLE
Adding a user via the users page does not work

### ISSUE THREAD

**Issue by DropTable00** [Ali229/Postit#20]
![image](https://user-images.githubusercontent.com/42593012/46824458-e0fb8500-cd5e-11e8-8e20-d8696edbf6a3.png)

With all fields filled out and valid, pressing the add user button does not do anything.

All browsers

Recreate: From the users page, click add user, fill out all fields with valid data, click add user at the bottom of the form.

**Comment by EagleZR** [comment]
Fixed backend crash and frontend bugs
