### ISSUE TITLE
Attempting to change a users account information does not work

### ISSUE THREAD

**Issue by DropTable00** [Ali229/Postit#21]
![image](https://user-images.githubusercontent.com/42593012/46825122-d80bb300-cd60-11e8-9521-3cd329ad243f.png)
After making an attempt to change a users account information the account does not update. Once attempted if you try to edit the account information again error messages as seen above appear in the edit user window.

All browsers.

Recreate: Change the value of all fields on an account. Click save changes and then try to edit the same user again.

**Comment by EagleZR** [comment]
Username is a primary key and should remain unchanged. Username field set to readonly. Closing
