### ISSUE TITLE
Clicking on the logo located on the navbar logs out the user

### ISSUE THREAD

**Issue by DropTable00** [Ali229/Postit#28]
![image](https://user-images.githubusercontent.com/42593012/46965227-3c3bb900-d078-11e8-9153-912c21c603e4.png)
From any page if a logged in user clicks the logo shown in the picture above they are logged out and returned to the login page.

All browsers.

Recreate: log in with any account click the logo located at the far left side of the nav bar.

**Comment by EagleZR** [comment]
Fixed with latest commit
