### ISSUE TITLE
Approved transactions to not appear in accounts

### ISSUE THREAD

**Issue by DropTable00** [Ali229/Postit#49]
![image](https://user-images.githubusercontent.com/42593012/47674942-e5150880-db8e-11e8-8cbc-ef41761841b2.png)
![image](https://user-images.githubusercontent.com/42593012/47675093-62407d80-db8f-11e8-9f53-8b0d48f3b3aa.png)

If a user approves a transaction, it does not appear in the account when viewed.

Recreate: Approve a new transaction from the journal page. Navigate to the chart of accounts and click on an account that was effected by the approved transaction.

**Comment by EagleZR** [comment]
The posted transactions are now shown, but the running balance does not show yet

**Comment by EagleZR** [comment]
The running balance is now shown as well
