### ISSUE TITLE
Cannot sort columns on the journal page

### ISSUE THREAD

**Issue by DropTable00** [Ali229/Postit#50]
![image](https://user-images.githubusercontent.com/42593012/47682318-67f38e80-dba2-11e8-9be3-496a615e3731.png)
 
Clicking a column does not sort by ascending/descending order. There is no effect when clicking the column.

Effects all browsers.

Recreate: Visit the journal page as a manager and click on the title of any column.

**Comment by EagleZR** [comment]
Fixed
