### ISSUE TITLE
Logging out and logging back in with another account has unexpected results

### ISSUE THREAD

**Issue by DropTable00** [Ali229/Postit#55]
![image](https://user-images.githubusercontent.com/42593012/48153063-5f324500-e293-11e8-9dd0-570ddb9ca041.png)
Upon logging out from the accountant user and attempting to log back in as a manager the above picture is the result. The issues seems unpredictable and is not always reproducible. It occurs unexpectedly and randomly. Additionally, the user is taken to the same page as the previous user upon switching accounts.
![image](https://user-images.githubusercontent.com/42593012/48153218-bcc69180-e293-11e8-8d2a-d0f1afc1f1ee.png)

**Comment by DropTable00** [comment]
Trying to login as our usual manager account does not work because the password is expired. Once you fail to login and enter admin credentials that do work you will be logged in as the manager that failed to login previously.

**Comment by EagleZR** [comment]
User information was being stored twice. It's been cleaned up to only pull from localstorage
